# Versioned overlays for the minecraft image.
#
# Discovery exposes `minecraft_<key>` for every version key and `minecraft` as
# an alias for the version named in `default`.
#
# Each variant picks mods by Modrinth slug in `services.minecraft.mods`.
# The per-version catalog is loaded from ./mods/<version>.json
# (generated by tools/update-mods.py). Cross-version baseline mods come from
# ./mods/common.json via the image base (./default.nix).
{ lib, artifacts, ... }:
let
  default = "26.1.2-fabric";

  catalogFor = ver: builtins.fromJSON (builtins.readFile ./mods/${ver}.json);

  variants = {
    "26w17a-fabric" = {
      loader = "fabric";
      version = "26.2-snapshot-5";
      loaderVersion = "0.19.2";
      installerVersion = "1.1.1";
      mods = [
        "fabric-api"
        "c2me-fabric"
      ];
    };

    "26.1.2-fabric" = {
      loader = "fabric";
      version = "26.1.2";
      loaderVersion = "0.19.2";
      installerVersion = "1.1.1";
      mods = [
        "fabric-api"
        "lithium"
        "c2me-fabric"
        "krypton"
        "ferrite-core"
        "servercore"
        "vmp-fabric"
        "clumps"
        "spark"
        "grimac"
      ];
    };

    "1.21.11-fabric" = {
      loader = "fabric";
      version = "1.21.11";
      loaderVersion = "0.19.2";
      installerVersion = "1.1.1";
      mods = [
        "fabric-api"
        "terrain-diffusion"
      ];
    };

    "1.21.11-paper" = {
      loader = "paper";
      version = "1.21.11";
      build = 69;
      mods = [ ];
    };
  };

  mkVariant =
    tag:
    {
      loader,
      mods,
      version,
      ...
    }@cfg:
    let
      loaderCfg = builtins.removeAttrs cfg [
        "loader"
        "mods"
      ];
    in
    {
      ix.image.tag = tag;
      services.minecraft = {
        mods = lib.genAttrs mods (_: { });
        modCatalog = artifacts.attachArtifactSources (catalogFor version);
      };
      services.minecraft.${loader} = loaderCfg // {
        enable = true;
        src = artifacts.minecraft.servers.${tag};
      };
    };
in
{
  inherit default;
}
// lib.mapAttrs mkVariant variants
