"""Type stubs for the native PyO3 module.

Hand-maintained to mirror packages/tui-py/src/. Keep in sync when adding or
changing PyO3 bindings — pyright/mypy use this file to type-check callers.
The async methods return native asyncio-awaitable coroutines produced by
pyo3-async-runtimes; awaiting them drives the underlying tokio future.
"""

from __future__ import annotations

from collections.abc import Awaitable
from typing import TypeAlias

import numpy as np
from numpy.typing import NDArray

__version__: str

#: A cell color: `None` is the terminal default, an `int` is a palette index,
#: an `(r, g, b)` tuple is truecolor.
_Color: TypeAlias = int | tuple[int, int, int] | None

class StyledCell:
    """A single terminal cell: character plus VT100 styling."""

    @property
    def char(self) -> str: ...
    @property
    def fg(self) -> _Color: ...
    @property
    def bg(self) -> _Color: ...
    @property
    def bold(self) -> bool: ...
    @property
    def italic(self) -> bool: ...
    @property
    def underline(self) -> bool: ...
    @property
    def inverse(self) -> bool: ...
    def __repr__(self) -> str: ...

class TuiInstance:
    """A handle to a single spawned TUI process. Spawning is the constructor."""

    def __init__(
        self,
        command: str,
        args: list[str] | None = ...,
        rows: int | None = ...,
        cols: int | None = ...,
        scrollback_lines: int | None = ...,
    ) -> None: ...
    @staticmethod
    def list_all() -> list[TuiInstance]: ...
    @property
    def id(self) -> str: ...
    @property
    def command(self) -> str: ...
    @property
    def args(self) -> list[str]: ...
    @property
    def cols(self) -> int: ...
    @property
    def rows(self) -> int: ...
    @property
    def scrollback_limit(self) -> int: ...

    # --- sync I/O ---------------------------------------------------------
    def write(self, data: str) -> None: ...
    def read_viewport(self) -> list[str]: ...
    def read_scrollback(self) -> list[str]: ...
    def read_full(self) -> tuple[list[str], list[str]]: ...
    def read_blocking(self, timeout_ms: int) -> list[str]: ...
    def read_chars_array(self) -> NDArray[np.uint32]: ...
    def read_styled_cells(self) -> list[list[StyledCell]]: ...

    # --- async I/O (native pyo3-async-runtimes coroutines) ----------------
    def write_async(self, data: str) -> Awaitable[None]: ...
    def read_viewport_async(self) -> Awaitable[list[str]]: ...
    def read_scrollback_async(self) -> Awaitable[list[str]]: ...
    def read_full_async(self) -> Awaitable[tuple[list[str], list[str]]]: ...
    def read_blocking_async(self, timeout_ms: int) -> Awaitable[list[str]]: ...
    def read_chars_array_async(self) -> Awaitable[NDArray[np.uint32]]: ...
    def read_styled_cells_async(self) -> Awaitable[list[list[StyledCell]]]: ...
    def __repr__(self) -> str: ...
