{
  lib,
  ix,
  codex,
  symlinkJoin,
  runCommand,
  writeText,
  runtimeShell,
  gnugrep,
  binName ? "codex",

  # Forced config: codex `-c key=value` overrides applied on EVERY invocation.
  # `-c` is codex's highest-precedence layer (above ~/.codex/config.toml), so use
  # this ONLY for wrapper INVARIANTS the user must not silently lose. The one we
  # bake: turn off the startup update check, since the store binary is read-only
  # and the wrapper owns the version pin, so the check only ever costs a network
  # round-trip it can never act on. Anything security-shaped (sandbox mode,
  # approval policy) is left to the user's config and codex's requirements layer.
  forcedSettings ? {
    check_for_update_on_startup = false;
  },

  # Soft defaults: codex `-c key=value` flags injected ONLY when the user's
  # config.toml does not already configure that sub-namespace, so an explicit
  # user value always wins (a bare `-c` would otherwise outrank the file layer,
  # which is wrong for a tunable). Detection is per second-segment token (the
  # feature/table a user would set): a config that mentions `multi_agent_v2`
  # keeps the wrapper's v2 defaults out, one that mentions `max_depth` keeps the
  # depth default out. A user's own later `-c` still wins over both.
  #
  # Default: a much higher multi-agent fan-out than stock. Run the v2 runtime
  # (stock default 4 = root + 3 subagents); 16 => root + 15 concurrent subagents.
  # v2 REJECTS `agents.max_threads` ("cannot be set when multi_agent_v2 is
  # enabled"), so the cap lives under the v2 feature; only `agents.max_depth` is
  # still read under v2 (3 => parent -> child -> grandchild -> great-grandchild).
  settings ? {
    features.multi_agent_v2 = {
      enabled = true;
      max_concurrent_threads_per_session = 16;
    };
    agents.max_depth = 3;
  },
}:
let
  inherit (lib)
    attrNames
    concatMap
    elemAt
    escapeShellArgs
    head
    length
    mapAttrsToList
    splitString
    ;

  realCodex = lib.getExe codex;

  # `key=<toml scalar>` for one flattened leaf; codex parses each `-c` value as
  # TOML. `ix.attrs.flattenToDotted` + `ix.toml.scalar` are the shared primitives
  # (lib/util); only the `--config` spelling and the forced/soft split below are
  # codex-specific glue.
  kvOf = flat: mapAttrsToList (key: value: "${key}=${ix.toml.scalar value}") flat;

  forcedKv = kvOf (ix.attrs.flattenToDotted forcedSettings);

  softFlat = ix.attrs.flattenToDotted settings;
  softKv = kvOf softFlat;
  # Per-key detection token: the second dotted segment (the feature/table a user
  # sets), or the whole key for a top-level leaf. Parallel to `softKv`, since
  # both walk `attrNames` in the same sorted order.
  softTok = map (
    key:
    let
      segs = splitString "." key;
    in
    if length segs >= 2 then elemAt segs 1 else head segs
  ) (attrNames softFlat);

  forcedInit = escapeShellArgs (concatMap (kv: [ "--config" kv ]) forcedKv);

  wrapper = writeText "codex-wrapper.sh" ''
    #!${runtimeShell}
    # Generated by packages/codex/default.nix. Forced `-c` invariants ride every
    # invocation; soft defaults inject only when the user's config.toml leaves
    # that sub-namespace unset, so an explicit user value wins. Ours come before
    # "$@", so a user's own later `-c` still wins (codex is last-wins within `-c`).
    cfg="''${CODEX_HOME:-''${HOME}/.codex}/config.toml"
    flags=( ${forcedInit} )

    soft_tok=( ${escapeShellArgs softTok} )
    soft_kv=( ${escapeShellArgs softKv} )
    i=0
    while [ "$i" -lt "''${#soft_kv[@]}" ]; do
      tok="''${soft_tok[$i]}"
      if [ -r "$cfg" ] && ${gnugrep}/bin/grep -Eq "^[^#]*\b''${tok}\b" "$cfg"; then
        : # user configures this sub-namespace; leave the wrapper default out
      else
        flags+=( --config "''${soft_kv[$i]}" )
      fi
      i=$((i + 1))
    done

    exec -a "$0" ${realCodex} "''${flags[@]}" "$@"
  '';
in
symlinkJoin {
  name = "codex-${codex.version}";
  paths = [ codex ];
  # symlinkJoin links the whole codex output (libexec, completions, ...); we only
  # replace the entrypoint with our wrapper so the baked defaults ride every
  # invocation while everything else stays pristine.
  postBuild = ''
    rm -f $out/bin/${binName}
    install -m755 ${wrapper} $out/bin/${binName}
  '';
  meta = codex.meta // {
    description = "${codex.meta.description or "OpenAI Codex CLI"} (index wrapper with baked defaults)";
    mainProgram = binName;
  };

  # Argv/precedence net for the wrapper, run against a stub codex so it is
  # offline and instant. Guards the soft-default contract: forced invariants
  # always ride, a soft default is injected when its sub-namespace is unset and
  # withheld when the user's config.toml sets it, a bare token in a comment does
  # not gate, and user argv passes through after our flags.
  passthru.tests.wrapper = runCommand "codex-wrapper-test" { } ''
    stub="$PWD/stub"
    printf '%s\n' '#!${runtimeShell}' 'for a in "$@"; do printf "%s\n" "$a"; done' > "$stub"
    chmod +x "$stub"
    sed "s|${realCodex}|$stub|" ${wrapper} > wrap
    chmod +x wrap

    fail() { echo "codex wrapper test: $1" >&2; echo "--- argv ---" >&2; printf '%s\n' "$2" >&2; exit 1; }
    has() { printf '%s\n' "$1" | ${gnugrep}/bin/grep -qF "$2"; }

    home=$(mktemp -d)
    got=$(CODEX_HOME="$home" ./wrap)
    for need in \
      check_for_update_on_startup=false \
      features.multi_agent_v2.enabled=true \
      features.multi_agent_v2.max_concurrent_threads_per_session=16 \
      agents.max_depth=3; do
      has "$got" "$need" || fail "no config: missing $need" "$got"
    done

    home=$(mktemp -d)
    printf '%s\n' '[features.multi_agent_v2]' 'enabled = false' > "$home/config.toml"
    got=$(CODEX_HOME="$home" ./wrap)
    has "$got" features.multi_agent_v2.enabled=true && fail "user set v2: should withhold v2 default" "$got"
    has "$got" agents.max_depth=3 || fail "user set v2: max_depth default should remain" "$got"
    has "$got" check_for_update_on_startup=false || fail "user set v2: forced flag missing" "$got"

    home=$(mktemp -d)
    printf '%s\n' '[agents]' 'max_depth = 5' > "$home/config.toml"
    got=$(CODEX_HOME="$home" ./wrap)
    has "$got" agents.max_depth=3 && fail "user set max_depth: should withhold depth default" "$got"
    has "$got" features.multi_agent_v2.enabled=true || fail "user set max_depth: v2 default should remain" "$got"

    home=$(mktemp -d)
    printf '%s\n' '# a comment mentioning multi_agent_v2 must not gate' > "$home/config.toml"
    got=$(CODEX_HOME="$home" ./wrap)
    has "$got" features.multi_agent_v2.enabled=true || fail "comment mention should not gate" "$got"

    home=$(mktemp -d)
    got=$(CODEX_HOME="$home" ./wrap -c 'model="o3"' exec hi)
    has "$got" 'model="o3"' || fail "user argv passthrough missing" "$got"

    mkdir -p $out
  '';
}
